crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('help/', HelpView.as_view(), name='help'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('customer/change/<int:id>/', CustomerChangeView.as_view(), name='customer-change'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('documents/add/<int:cid>/', DocumentsAddView.as_view(), name='documents-add'),
    path('requests/add/', RequestsAddView.as_view(), name='request-add'),
    path('requests/list/', RequestsListView.as_view(), name='request-list'),
    path('messages/', MessagesView.as_view(), name='messages'),
    path('messages/<int:mid>/', MessageDoneView.as_view(), name='message-done'),
    path('invoices/list/', InvoiceListView.as_view(), name='invoice-list'),
    ]

uifcrm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('crm.urls', namespace='crm')),
    path('staff/', include('staff.urls', namespace='staff')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

crm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

def documents_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"{instance.customer.company}/{filename}"
    # "{0}/{1}".format(instance.user.id, filename)


class BaseModel(models.Model):
    user_modified = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_modified',
        null=True,
        blank=True,
        verbose_name='کاربر ویرایش'
        )
    user_created = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_created',
        null=True,
        blank=True,
        verbose_name='کاربر ایجاد'
        )
    created_date = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    modified_date = models.DateTimeField(verbose_name='تاریخ تغییرات', auto_now=True)

    class Meta:
        abstract = True


class CustomerModel(BaseModel):
    STATE_REAL = 'real'
    STATE_LEGAL = 'legal'
    STATE_CHOICES = (
        (STATE_REAL, 'حقیقی'),
        (STATE_LEGAL, 'حقوقی')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    sid = models.CharField(verbose_name='کد معین', max_length=50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    state = models.CharField(verbose_name='نوع مشارکت کننده', max_length=50, choices=STATE_CHOICES, default=STATE_REAL)
    firstname = models.CharField(verbose_name='نام', max_length=50)
    lastname = models.CharField(verbose_name='نام خانوادگی', max_length=50)
    fathername = models.CharField(verbose_name='نام پدر', max_length=50)
    code = models.CharField(verbose_name='کدملی', max_length=10)
    ceoname = models.CharField(verbose_name='نام مدیرعامل', max_length=100, null=True, blank=True)
    company = models.CharField(verbose_name='نام تجاری/شرکت', max_length=100)
    ncode = models.CharField(verbose_name='شناسه ملی', max_length=11, null=True, blank=True)
    mobile = models.CharField(verbose_name='موبایل', max_length=11)
    phone = models.CharField(verbose_name='تلفن', max_length=11, null=True, blank=True)
    fax = models.CharField(verbose_name='فکس', max_length=11, null=True, blank=True)
    email = models.EmailField(verbose_name='ایمیل', null=True, blank=True)
    postalcode = models.CharField(verbose_name='کد پستی', max_length=10)
    address = models.TextField(verbose_name='آدرس')

    def __str__(self):
        return f"{self.company}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["company", "code"], name='comcode'),
            models.UniqueConstraint(fields=["sid"], name='specid')
    ]
        verbose_name = 'مشارکت کننده'
        verbose_name_plural = 'مشارکت کنندگان'


class DocumentsModel(BaseModel):
    STATE_WAIT = 'wait'
    STATE_ACCEPT = 'accept'
    STATE_DENY = 'deny'
    STATE_CHOICES = (
        (STATE_WAIT, 'در انتظار بررسی'),
        (STATE_ACCEPT, 'قبول شده'),
        (STATE_DENY, 'رد شده')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_WAIT)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='مشارکت کننده')
    file = models.FileField(verbose_name='مدرک', upload_to=documents_directory_path)

    def __str__(self):
        if self.customer is not None:
            return f"{self.customer.company} - {self.file.name}"
        return self.file.name
    
    class Meta:
        verbose_name = 'مدرک'
        verbose_name_plural = 'مدارک'


class ExhibitionModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    sid = models.CharField(verbose_name='کد معین', max_length=50, null=True, blank=True)
    title = models.CharField(verbose_name='عنوان نمایشگاه', max_length=200)
    price = models.CharField(verbose_name='قیمت', max_length=20)
    value_added = models.CharField(verbose_name='ارزش افزوده', max_length=10)
    date = models.DateField(verbose_name='تاریخ برگزاری', null=True, blank=True)

    def __str__(self):
        return f"{self.title} - {self.date.year}"
    
    class Meta:
        verbose_name = 'نمایشگاه'
        verbose_name_plural = 'نمایشگاه‌ها'


class RequestModel(BaseModel):
    STATE_WAIT = 'wait'
    STATE_ACCEPT = 'accept'
    STATE_DENY = 'deny'
    STATE_CHOICES = (
        (STATE_WAIT, 'در انتظار بررسی'),
        (STATE_ACCEPT, 'قبول شده'),
        (STATE_DENY, 'رد شده')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_WAIT)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, verbose_name='مشارکت کننده')
    exhibition = models.ForeignKey(ExhibitionModel, on_delete=models.CASCADE, verbose_name='نمایشگاه')
    area = models.IntegerField(verbose_name='متراژ', default=0)
    rules = models.BooleanField(verbose_name='قوانین')
    is_active = models.BooleanField(verbose_name='فعال', default=True)

    def __str__(self):
        return f"{self.customer.company} - {self.exhibition.title}"
    
    class Meta:
        verbose_name = 'درخواست'
        verbose_name_plural = 'درخواست‌ها'


class MessagesModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, verbose_name='مشارکت کننده')
    text = models.TextField(verbose_name='متن پیام')

    def __str__(self):
        return f"{self.pk}.{self.customer.company} - ({self.customer.firstname} {self.customer.lastname})"
    
    class Meta:
        verbose_name = 'پیغام'
        verbose_name_plural = 'پیغام‌ها'


class MessageChangeModel(models.Model):
    message = models.ForeignKey(MessagesModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="پیغام اصلی")
    text = models.TextField(verbose_name='متن پیام')
    user_modified = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_modified',
        null=True,
        blank=True,
        verbose_name='کاربر ویرایش'
        )
    modified_date = models.DateTimeField(verbose_name='تاریخ تغییرات')

    def __str__(self):
        if self.message is not None:
            return f"{self.message.pk}.{self.message.customer.company} - ({self.message.customer.firstname} {self.message.customer.lastname})"
        return self.text
    
    class Meta:
        verbose_name = 'پیغام ویرایش شده'
        verbose_name_plural = 'پیغام‌های ویرایشی'


class InvoiceModel(BaseModel):
    STATE_PREPAYMENT = 'prepayment'
    STATE_PAID = 'paid'
    STATE_UNPAID = 'unpaid'
    STATE_CHOICES = (
        (STATE_PREPAYMENT, 'پیش پرداخت'),
        (STATE_PAID, 'پرداخت شده'),
        (STATE_UNPAID, 'پرداخت نشده')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_UNPAID)
    customer = models.ForeignKey(CustomerModel, on_delete=models.PROTECT, verbose_name="مشارکت کننده")
    amount = models.CharField(verbose_name="مبلغ", max_length=20)

    def __str__(self):
        return f"{self.customer.company} - شماره فاکتور: {self.pk}"
    
    class Meta:
        verbose_name = 'فاکتور'
        verbose_name_plural = 'فاکتورها'


class InvoiceItemModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    invoice = models.ForeignKey(InvoiceModel, on_delete=models.SET_NULL, verbose_name="فاکتور", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='مشارکت کننده')
    exhibition = models.ForeignKey(ExhibitionModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='نمایشگاه')
    price = models.CharField(verbose_name='مبلغ', max_length=20)
    area = models.IntegerField(verbose_name='متراژ', default=0)
    value_added = models.CharField(verbose_name='ارزش افزوده', max_length=10, default="0")
    discount = models.CharField(verbose_name='تخفیف', max_length=20, null=True, blank=True)
    total_price = models.CharField(verbose_name='مبلغ نهایی', max_length=20)
    description = models.TextField(verbose_name='توضیحات', null=True, blank=True)

    def __str__(self):
        if self.customer is not None:
            return f"{self.customer.company} - {self.exhibition.title} - {self.price}"
        return f"{self.area} - {self.total_price}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["exhibition", "customer"], name='excus')
    ]
        verbose_name = 'اقلام فاکتور'
        verbose_name_plural = 'اقلام فاکتورها'


class PaymentModel(BaseModel):
    STATE_CHECK = 'check'
    STATE_CASHE = 'cashe'
    STATE_POS = 'pos'
    STATE_CHOICES = (
        (STATE_CHECK, 'چک بانکی'),
        (STATE_CASHE, 'نقدی'),
        (STATE_POS, 'پوز بانکی')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_POS)
    invoice = models.ForeignKey(InvoiceModel, on_delete=models.PROTECT, verbose_name="فاکتور")
    amount = models.IntegerField(verbose_name="مبلغ", default=1000)
    cardnumber = models.CharField(verbose_name="شماره کارت/چک", max_length=32, null=True, blank=True)
    issuerbank = models.CharField(verbose_name="بانک صادرکننده", max_length=150, null=True, blank=True)
    name = models.CharField(verbose_name="مشخصات صاحب چک", max_length=150, null=True, blank=True)

crm/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

def is_code(value):
    if len(value) != 10 or not str(value).isnumeric():
        raise ValidationError('کد ملی صحیح نمی‌باشد!')
    
def is_mobile(value):
    if not str(value).isnumeric() or len(value) !=11 or str(value)[0] != '0':
        raise ValidationError('شماره موبایل صحیح نمی‌باشد!')
    
def is_phone(value):
    if not str(value).isnumeric() or len(value) !=11 or str(value)[0] != '0':
        raise ValidationError('شماره تلفن صحیح نمی‌باشد!')
    
def is_ncode(value):
    if len(value) != 10 or not str(value).isnumeric():
        raise ValidationError("شناسه ملی صحیح نمی‌باشد.")
    
def is_postal(value):
    if len(value) != 10 or not str(value).isnumeric():
        raise ValidationError('کد پستی صحیح نمی‌باشد!')


class CustomerAddForm(forms.ModelForm):
    ncode = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شناسه ملی شرکت/سازمان", validators=[is_ncode])
    phone = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره ثابت", validators=[is_phone])
    fax = forms.CharField(max_length=11, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="شماره فکس", validators=[is_phone])
    postalcode = forms.CharField(max_length=10, required=False, widget=forms.TextInput(attrs={'class':'form-control'}), label="کد پستی", validators=[is_postal])

    class Meta:
        model = CustomerModel
        fields = (
                  'state',
                  'firstname',
                  'lastname',
                  'fathername',
                  'ceoname',
                  'company',
                  'ncode',
                  'phone',
                  'fax',
                  'email',
                  'postalcode',
                  'address',
                  )
        widgets = {
            'state': forms.Select(attrs={'class':'form-control'}),
            'firstname': forms.TextInput(attrs={'class':'form-control'}),
            'lastname': forms.TextInput(attrs={'class':'form-control'}),
            'fathername': forms.TextInput(attrs={'class':'form-control'}),
            'ceoname': forms.TextInput(attrs={'class':'form-control'}),
            'company': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'address': forms.Textarea(attrs={'class':'form-control', 'rows':3}),
        }


class DocumentForm(forms.ModelForm):

    class Meta:
        model = DocumentsModel
        fields = (
            'file',
        )
        widgets = {
            'file': forms.FileInput(attrs={'value':'dd'}),
        }


class RequestsForm(forms.ModelForm):
    exhibition = forms.ModelChoiceField(
        queryset = ExhibitionModel.objects.filter(is_active=True),
        widget =forms.Select(attrs={'class':'form-control'}),
        required=True,
        label = 'عنوان نمایشگاه'
    )

    class Meta:
        model = RequestModel
        fields = (
            'customer',
            'exhibition',
            'area',
            'rules',
        )
        widgets = {
            'customer': forms.Select(attrs={'class':'form-control', 'required':True}),
            'area': forms.NumberInput(attrs={'class':'form-control'}),
            'rules': forms.CheckboxInput(attrs={'required':True})
        }

crm/templates/crm/customer-list.html
{% extends "base-c.html" %}
{% load jalali_tags %}
{% block title %}
لیست پروفایل‌های من
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h2>لیست پروفایل‌های من</h2>
                        <p>لطفاً از صحیح و بروز بودن اطلاعات خود اطمینان حاصل فرمایید!</p>
                        <p class="text-danger">برای مشارکت کنندگان حقوقی شناسه ملی شرکت/سازمان و نام مدیرعامل الزامی است!</p>
                    </div>
                </div>
            </div>
            {% if customer %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="table-responsive">
                                <table id="datatable" class="table table-bordered table-hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>نوع کاربر</th>
                                            <th>نام تجاری</th>
                                            <th>تاریخ</th>
                                            <th>وضعیت</th>
                                            <th>اقدامات</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for customer in customer %}
                                        <tr>
                                            <td>{% if customer.state == "legal" %}
                                                <h4><span class="badge badge-pill badge-info">{{ customer.get_state_display }}</span></h4>
                                                {% else %}
                                                <h4><span class="badge badge-pill badge-light">{{ customer.get_state_display }}</span></h4>
                                                {% endif %}
                                            </td>
                                            <td style="color:blueviolet">{{ customer.company }}</td>
                                            <td class="text-primary">{{ customer.created_date|to_jalali:'%Y/%m/%d' }}</td>
                                            <td>
                                                {% if customer.is_active %}
                                                <span class="badge badge-success">قبول</span>
                                                {% else %}
                                                <span class="badge badge-danger">غیرفعال</span>
                                                {% endif %}
                                            </td>
                                            <td><a href="{% url 'crm:customer-change' id=customer.pk %}">ویرایش</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <p class="h5">هنوز حساب تجاری ایجاد نکرده‌اید، جهت ایجاد حساب جدید از <a class="btn btn-info btn-xs" href="{% url 'crm:customer-add' %}">اینجا</a> اقدام کنید.</p>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

{% block script %}

{% endblock script %}

crm/templates/crm/documents.html
{% extends "base-c.html" %}
{% load jalali_tags %}
{% load static %}

{% block title %}
مدرک ها
{% endblock title %}

{% block content %}
<section>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h2>مدارک من</h2>
                <p>لطفا مدارک مورد نیاز جهت تایید و اعطاء مجوز به پروفایل شما برای رزرو غرفه در نمایشگاه‌ها را بارگذاری کنید.</p>
                <p>برای اشخاص حقیقی تصویر کارت ملی و مجوزها(پروانه کسب، مجوزتولید یا کارگاه و...) الزامی است.</p>
                <p>برای اشخاص حقوقی تصویر کارت ملی مدیرعامل و نماینده حقوقی و مجوزها الزامی است.</p>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6">
                        <form method="post" action="{% url 'crm:documents-add' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    {{ form.customer.label_tag }}
                                    {{ form.customer }}
                                    {% if form.label_tag.errors %}
                                        {% for error in form.label_tag.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group col-lg-6">
                                    {{ form.file.label_tag }}
                                    {{ form.file }}
                                    {% if form.label_tag.errors %}
                                        {% for error in form.label_tag.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                            <input type="submit" class="btn btn-success" value="ذخیره اطلاعات">
                        </form>
                    </div>
                    <div class="col-lg-6">
                        {% for doc in docs %}
                        <h5><a href="{{ doc.file.url}}">{{ doc.file.name }}</a><span class="float-right">{{ doc.get_state_display }}</span></h5>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

crm/templates/crm/index.html
{% extends "base-c.html" %}
{% load jalali_tags %}
{% load static %}

{% block title %}
صفحه اصلی | مدیریت حساب
{% endblock title %}

{% block content %}

<section id="page-content" class="background-light" data-bg-image="{% static 'images/p1.jpg' %}" style="min-height:700px">
    <div class="container">
        {% for mes in mes %}
                        {% if forloop.last %}
        <div class="alert alert-danger alert-dismissible fade show font-weight-bold" role="alert">
            شما <b>{{ forloop.counter }}</b> پیغام خوانده نشده دارید!
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
        {% endif %}
                    {% endfor %}

        <div class="grid-layout grid-1-columns" data-item="grid-item" data-margin="10">
            <div class="grid-item">
                <div class="widget widget-notification p-cb">
                    <h4 class="mb-0">حساب ها</h4>
                    {% for customer in customer %}
                        {% if forloop.last %}
                            <p>شما {{ forloop.counter }} حساب ایجاد شده دارید</p>
                        {% endif %}
                    {% endfor %}
                    {% if customer %}
                    <div class="row mt-5">
                        {% for customer in customer%}
                        <div class="col-lg-6">
                            <ul class="list-icon list-icon-caret list-icon-colored">
                                <li class="text-info"><b>نام تجاری:</b> {{ customer.company }}</li>
                            {% if customer.state == "legal"%}
                                {% if customer.ceoname %}
                                    <li><b>نوع حساب:</b> {{ customer.get_state_display }}</li>
                                    <li><b>نام مدیرعامل:</b> {{ customer.ceoname }}</li>
                                    <li><b>شناسه ملی:</b> {{ customer.ncode }}</li>
                                    <li><b>شماره موبایل:</b> {{ customer.mobile }}</li>
                                {% endif %}
                            {% else %}
                                <li><b>نوع حساب:</b> {{ customer.get_state_display }}</li>
                                <li><b>نام و نشان:</b> {{ customer.firstname }} {{ customer.lastname }}</li>
                                <li><b>کد ملی:</b> {{ customer.code }}</li>
                                <li><b>شماره موبایل:</b> {{ customer.mobile }}</li>
                            {% endif %}
                        </ul>

                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <div class="row">
                        <div class="col-lg-6">
                            <h5><a href="{% url 'crm:customer-add' %}" class="text-info" >شما حساب فعال ندارید لطفاً حساب جدید ایجاد کنید >></a></h5>
                        </div>
                    </div>
                    {% endif %}

                    <hr>
                    <a href="{% url 'crm:customer-list' %}" class="text-theme">مشاهده حساب ها</a>
                </div>
            </div>
        </div>
        <div class="grid-layout grid-2-columns" data-item="grid-item" data-margin="10">
            <div class="grid-item">
                <div class="widget widget-notification p-cb">
                    <h4 class="mb-0">پیغام‌ ها</h4>
                    {% for mes in mes %}
                        {% if forloop.last %}
                            <p class="text-danger">شما {{ forloop.counter }} پیغام جدید دارید</p>
                        {% endif %}
                    {% endfor %}
                    {% if mes %}
                    {% for mes in mes %}
                    {% if forloop.counter < 5 %}
                        <div class="notification-item notification-new">
                            <div class="notification-meta">
                                <a href="#">{{ mes.text|safe|truncatewords:8 }}</a>
                                <span>{{ mes.created_date|to_jalali:'%Y/%m/%d' }}</span>
                            </div>
                        </div>
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    <div>
                        <p>شما پیغام جدید ندارید.</p>
                    </div>
                    {% endif %}

                    <hr>
                    <a href="{% url 'crm:messages' %}" class="text-theme">مشاهده همه پیغام ها</a>
                </div>
            </div>
            <div class="grid-item">

                <div class="widget widget-archive p-cb">
                    <h4 class="mb-0">فاکتورها</h4>
                    {% if invoices %}
                    {% for invoice in invoices %}
                        {% if forloop.last %}
                        <p class="text-danger">شما {{ forloop.counter }} فاکتور پرداخت نشده دارید</p>
                        {% endif %}
                    {% endfor %}
                    <ul class="list list-lines">
                        {% for invoice in invoices %}
                        {% if forloop.counter < 3 %}
                        <li>{{ forloop.counter }} - نمایشگاه {{ invoice.exhibition.title }} به مبلغ {{ invoice.total_price }} ریال<a class="btn btn-xs" style="float:left">پرداخت</a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p class="">شما فاکتوری برای پرداخت ندارید.</p>
                    {% endif %}
                    <hr>
                    <a href="{% url 'crm:invoice-list' %}" class="text-theme">مشاهده همه فاکتورها</a>
                </div>

            </div>
        </div>

    </div>
</section>
{% endblock content %}

crm/templates/crm/invoice-list.html
{% extends "base-c.html" %}
{% load jalali_tags %}
{% load static %}
{% load humanize %}

{% block title %}
فاکتورها
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h2>فاکتورهای من</h2>
                        <p>مشارکت کننده گرامی در صورت تسویه حساب، فاکتور نهایی برای شما صادر خواهد شد.</p>
                    </div>
                </div>
            </div>
            {% if invoices %}
            <div class="col-lg-12">
                {% for invoice in invoices %}
                <div class="card">
                    <div class="card-body">
                        <h4><b>شماره:</b> {{ invoice.pk }}</h4>
                        <h5><b>نام تجاری:</b> {{ invoice.customer.company }} <span class="float-right"><b>تاریخ:</b> {{ invoice.created_date|to_jalali:"%Y/%m/%d" }}</span></h5>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>عنوان نمایشگاه</th>
                                    <th>متراژ(متر مربع)</th>
                                    <th>قیمت هرمترمربع (ریال)</th>
                                    <th>ارزش افزوده (درصد)</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in invoice.invoiceitemmodel_set.all %}
                                <tr>
                                    <td>{{ item.exhibition.title }}</td>
                                    <td>{{ item.area }}</td>
                                    <td>{{ item.price|intcomma:False }}</td>
                                    <td>{{ item.value_added }} درصد</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="3"></td>
                                    <td><b>کل:</b> {{ invoice.amount|intcomma:False }}</td>
                                </tr>
                            </tbody>
                        </table>
                        {% if invoice.state == "paid" %}
                        <p class="text-success"><b>توضیحات:</b> <i class="fa fa-check-circle"></i> {{ invoice.get_state_display }}</p>
                        {% else %}
                        <p class="text-danger"><b>توضیحات:</b> <i class="fa fa-minus-circle"></i> {{ invoice.get_state_display }}</p>
                        <a class="btn btn-sm btn-danger text-right">پرداخت</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <p class="h5">هیچ فاکتوری برای شما ثبت نشده است!</p>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}