accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('verify/<str:code>/', MobileVerifyView.as_view(), name='verify'),
    path('change/mobile/<str:code>/', ChangeMobileView.as_view(), name='change-mobile'),
    path('re-token/<str:code>/', ReTokenView.as_view(), name='re-token'),

    ]

crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('help/', HelpView.as_view(), name='help'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('customer/change/<int:id>/', CustomerChangeView.as_view(), name='customer-change'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('documents/add/<int:cid>/', DocumentsAddView.as_view(), name='documents-add'),
    path('requests/add/', RequestsAddView.as_view(), name='request-add'),
    path('requests/list/', RequestsListView.as_view(), name='request-list'),
    path('messages/', MessagesView.as_view(), name='messages'),
    path('messages/<int:mid>/', MessageDoneView.as_view(), name='message-done'),
    path('invoices/list/', InvoiceListView.as_view(), name='invoice-list'),
    ]

staff/urls.py
from django.urls import path
from .views import *

app_name = 'staff'

urlpatterns = [
    path('', Test.as_view(), name='test'),
    path('home/', HomeView.as_view(), name='home'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/change/<int:cid>/', CustomerChangeView.as_view(), name='customer-change'),
    path('request/list/', RequestListView.as_view(), name='request-list'),
    path('request/details/<int:rid>/', RequestDetailsView.as_view(), name='request-details'),
    path('invoice/add/', InvoiceAddView.as_view(), name='invoice-add'),
    path('invoice/list/', InvoiceListView.as_view(), name='invoice-list'),
    path('invoice/unpaid/', InvoiceUnpaidView.as_view(), name='invoice-unpaid'),
    path('invoice/details/<int:iid>/', InvoiceDetailsView.as_view(), name='invoice-details'),
    path('invoice/edit/<int:iid>/', InvoiceEditView.as_view(), name='invoice-edit'),
    path('document/list/', DocumentsListView.as_view(), name='documents-list'),
    path('document/add/<int:id>/', DocumentsAddView.as_view(), name='documents-add'),
    path('document/del/<int:fid>/', DocumentsDelView.as_view(), name='documents-del'),
    path('document/accept/<int:fid>/', DocumentsAcceptView.as_view(), name='documents-accept'),
    path('document/deny/<int:fid>/', DocumentsDenyView.as_view(), name='documents-deny'),
    path('message/list/', MessagesListView.as_view(), name='message-list'),
    path('message/add/', MessageAddView.as_view(), name='message-add'),
    path('message/change/<int:mid>/', MessageChangeView.as_view(), name='message-change'),
    path('exhibition/add/', ExhibitionAddView.as_view(), name='exhibition-add'),
    path('exhibition/list/', ExhibitionListView.as_view(), name='exhibition-list'),
    path('exhibition/details/<int:eid>/', ExhibitionDetailsView.as_view(), name='exhibition-details'),
    path('exhibition/status/<int:id>/', ExhibitionStatusView.as_view(), name='exhibition-status'),
    path('payment/list/', PaymentListView.as_view(), name='payment-list'),
    path('payment/add/<int:id>/', PaymentAddView.as_view(), name='payment-add'),
    path('payment/edit/<int:id>/', PaymentEditView.as_view(), name='payment-edit'),
    ]

uifcrm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('crm.urls', namespace='crm')),
    path('staff/', include('staff.urls', namespace='staff')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/base-c.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="example" />
    <meta name="description" content="سامانه مشتریان شرکت نمایشگاه بین‌المللی ارومیه">
    <link rel="icon" type="image/png" href="{% static 'images/fav-logo.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock title %}</title>

    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
</head>

<body data-icon="17">

    <div class="body-inner">
        <header id="header" data-fullwidth="true" class="header-always-fixed">
            <div class="header-inner">
                <div class="container">
                    <div id="logo">
                        <a href="index.html">
                            <span class="logo-default">UIF</span>
                            <span class="logo-dark">UIF</span>
                        </a>
                    </div>
                        
                    <div class="header-extras">
                        <ul>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-user"></i></a>
                                    <ul class="p-dropdown-content">
                                        <ul class="text-center">
                                            {% comment %} <li><a href="#"><i class="icon-mail"></i>پیام ها</a></li> {% endcomment %}
                                            <li><a href="#"><i class="icon-settings"></i>تنظیمات</a></li>
                                            <li>
                                                <a href="{% url 'accounts:signout' %}"><i class="icon-log-out"></i>خروج</a>
                                            </li>
                                        </ul>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a href="{% url 'crm:messages' %}"> <i class="icon-bell"></i><sup style="top:-0.6em; font-size:1.2em"><b class="text-danger"></b></sup></a>
                            </li>
                        </ul>
                    </div>
                        
                        
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>

                    <div id="mainMenu" class="menu-center">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{% url 'crm:index' %}">خانه</a></li>
                                    <li class="dropdown"><a href="#">پروفایل‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'crm:customer-list' %}">لیست همه</a> </li>
                                            <li><a href="{% url 'crm:customer-add' %}"> جدید</a> </li>
                                            {% comment %} <li><a href="{% url 'crm:documents-list' %}">مدارک</a> </li> {% endcomment %}
                                        </ul>
                                    </li>
                                    <li class="dropdown"><a href="#">مالی</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'crm:invoice-list' %}">فاکتورها</a></li>
                                            <li><a href="#">پرداخت‌ها</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown"><a href="#">درخواست‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'crm:request-list' %}">لیست همه</a></li>
                                            <li><a href="{% url 'crm:request-add' %}">جدید</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'crm:messages' %}">پیام‌ها</a>  </li>
                                    <li><a href="{% url 'crm:help' %}">راهنما</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        {% block content %}{% endblock content %}
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="icon-box effect small clean">
                                <div class="icon">
                                    <a href="#"><i class="icon-clock"></i></a>
                                </div>
                                <h3>روزهای کاری</h3>
                                <p><strong>شنبه - چهارشنبه</strong>
                                    <br>15:00 صبح - 08:00 عصر</p>
                                <p><strong>پنج شنبه ها</strong>
                                    <br>13:00 صبح - 08:00 عصر</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="icon-box effect small clean">
                                <div class="icon">
                                    <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                                </div>
                                <h3>موقعیت مکانی</h3>
                                <p><strong>آدرس سایت نمایشگاهی : </strong>
                                    <br> ارومیه، خیابان نبوت،
                                    <br> خیابان براعتی، پارک جنگلی،
                                    <br>محل دائمی نمایشگاه‌‌ها،
                                    <br>ساختمان اداری
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="icon-box effect small clean">
                                <div class="icon">
                                    <a href="#"><i class="icon-phone"></i></a>
                                </div>
                                <h3>شماره تماس پشتیبانی</h3>
                                <p><strong>تلفن : </strong>
                                    <br> 02155667788
                                    <br> 02166554433
                                    <br>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6">

                            <div class="social-icons social-icons-colored float-left">
                                <img src="{% static 'images/uif-f.png' %}" alt="logo" style="max-width:70px">
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <div class="copyright-text text-center">© تمام حقوق این سامانه متعلق به شرکت نمایشگاه بین‌المللی ارومیه می‌باشد.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    
  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Include Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
   
{% block script %}{% endblock script %}
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="example" />
    <meta name="description" content="سامانه مشتریان شرکت نمایشگاه بین‌المللی ارومیه">
    <link rel="icon" type="image/png" href="images/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}{% endblock title %}</title>

    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/rtl.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</head>
<body>
</head>

<body>

    <div class="body-inner">
        <header id="header" data-fullwidth="true" class="header-always-fixed">
            <div class="header-inner">
                <div class="container">
                    <div id="logo">
                        <a href="index.html">
                            <span class="logo-default">UIF</span>
                            <span class="logo-dark">UIF</span>
                        </a>
                    </div>
                        
                        
                    <div id="search"><a id="btn-search-close" class="btn-search-close" aria-label="Close search form"><i class="icon-x"></i></a>
                        <form class="search-form" action="search-results-page.html" method="get">
                            <input class="form-control" name="q" type="text" placeholder="جستجو کنید ..." />
                            <span class="text-muted">جستجو را شروع کنید و کلید "Enter" را بزنید یا برای خروج دکمه "ESC" را بزنید</span>
                        </form>
                    </div>
                        
                        
                    <div class="header-extras">
                        <ul>
                            <li>
                                <a id="btn-search" href="#"> <i class="icon-search"></i></a>
                            </li>
                            <li>
                                <div class="p-dropdown">
                                    <a href="#"><i class="icon-user-plus h4"></i></a>
                                    <ul class="p-dropdown-content text-center">
                                        <li><a href="#"><i class="icon-log-out"></i>خروج</a>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                        
                        
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>

                    <div id="mainMenu" class="menu-center">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="{% url 'staff:home' %}">خانه</a></li>
                                    <li class="dropdown"><a href="#">مشارکت کنندگان</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'staff:customer-list' %}">لیست همه</a> </li>
                                            <li><a href="{% url 'staff:customer-add' %}"> جدید</a> </li>
                                            <li><a href="{% url 'staff:documents-list' %}">مدارک</a> </li>
                                        </ul>
                                    </li>
                                    <li class="dropdown"><a href="#">مالی</a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown-submenu"><a href="#">فاکتورها</a>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{% url 'staff:invoice-list' %}">لیست همه</a></li>
                                                    <li><a href="{% url 'staff:invoice-unpaid' %}">پرداخت نشده‌ها</a></li>
                                                    <li><a href="{% url 'staff:invoice-add' %}">جدید</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'staff:payment-list' %}">پرداخت‌ها</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown"><a href="#">نمایشگاه‌ها</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'staff:exhibition-list' %}">لیست همه</a></li>
                                            <li><a href="{% url 'staff:exhibition-add' %}">جدید</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'staff:request-list' %}">درخواست‌ها</a></li>
                                    <li><a href="{% url 'staff:message-list' %}">پیام‌ها</a> </li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </header>
        {% block content %}{% endblock content %}
    </div>

    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>

    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
    
  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Include Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
   
{% block script %}{% endblock script %}
</body>

</html>