crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('help/', HelpView.as_view(), name='help'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('customer/change/<int:id>/', CustomerChangeView.as_view(), name='customer-change'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('documents/add/<int:cid>/', DocumentsAddView.as_view(), name='documents-add'),
    path('requests/add/', RequestsAddView.as_view(), name='request-add'),
    path('requests/list/', RequestsListView.as_view(), name='request-list'),
    path('messages/', MessagesView.as_view(), name='messages'),
    path('messages/<int:mid>/', MessageDoneView.as_view(), name='message-done'),
    path('invoices/list/', InvoiceListView.as_view(), name='invoice-list'),
    ]

staff/urls.py
from django.urls import path
from .views import *

app_name = 'staff'

urlpatterns = [
    path('', Test.as_view(), name='test'),
    path('home/', HomeView.as_view(), name='home'),
    path('customer/list/', CustomerListView.as_view(), name='customer-list'),
    path('customer/add/', CustomerAddView.as_view(), name='customer-add'),
    path('customer/change/<int:cid>/', CustomerChangeView.as_view(), name='customer-change'),
    path('request/list/', RequestListView.as_view(), name='request-list'),
    path('request/details/<int:rid>/', RequestDetailsView.as_view(), name='request-details'),
    path('invoice/add/', InvoiceAddView.as_view(), name='invoice-add'),
    path('invoice/list/', InvoiceListView.as_view(), name='invoice-list'),
    path('invoice/unpaid/', InvoiceUnpaidView.as_view(), name='invoice-unpaid'),
    path('invoice/details/<int:iid>/', InvoiceDetailsView.as_view(), name='invoice-details'),
    path('invoice/edit/<int:iid>/', InvoiceEditView.as_view(), name='invoice-edit'),
    path('document/list/', DocumentsListView.as_view(), name='documents-list'),
    path('document/add/<int:id>/', DocumentsAddView.as_view(), name='documents-add'),
    path('document/del/<int:fid>/', DocumentsDelView.as_view(), name='documents-del'),
    path('document/accept/<int:fid>/', DocumentsAcceptView.as_view(), name='documents-accept'),
    path('document/deny/<int:fid>/', DocumentsDenyView.as_view(), name='documents-deny'),
    path('message/list/', MessagesListView.as_view(), name='message-list'),
    path('message/add/', MessageAddView.as_view(), name='message-add'),
    path('message/change/<int:mid>/', MessageChangeView.as_view(), name='message-change'),
    path('exhibition/add/', ExhibitionAddView.as_view(), name='exhibition-add'),
    path('exhibition/list/', ExhibitionListView.as_view(), name='exhibition-list'),
    path('exhibition/details/<int:eid>/', ExhibitionDetailsView.as_view(), name='exhibition-details'),
    path('exhibition/status/<int:id>/', ExhibitionStatusView.as_view(), name='exhibition-status'),
    path('payment/list/', PaymentListView.as_view(), name='payment-list'),
    path('payment/add/<int:id>/', PaymentAddView.as_view(), name='payment-add'),
    path('payment/edit/<int:id>/', PaymentEditView.as_view(), name='payment-edit'),
    ]

uifcrm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('crm.urls', namespace='crm')),
    path('staff/', include('staff.urls', namespace='staff')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

crm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

def documents_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"{instance.customer.company}/{filename}"
    # "{0}/{1}".format(instance.user.id, filename)


class BaseModel(models.Model):
    user_modified = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_modified',
        null=True,
        blank=True,
        verbose_name='کاربر ویرایش'
        )
    user_created = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_created',
        null=True,
        blank=True,
        verbose_name='کاربر ایجاد'
        )
    created_date = models.DateTimeField(verbose_name='تاریخ ایجاد', auto_now_add=True)
    modified_date = models.DateTimeField(verbose_name='تاریخ تغییرات', auto_now=True)

    class Meta:
        abstract = True


class CustomerModel(BaseModel):
    STATE_REAL = 'real'
    STATE_LEGAL = 'legal'
    STATE_CHOICES = (
        (STATE_REAL, 'حقیقی'),
        (STATE_LEGAL, 'حقوقی')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    sid = models.CharField(verbose_name='کد معین', max_length=50, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    state = models.CharField(verbose_name='نوع مشارکت کننده', max_length=50, choices=STATE_CHOICES, default=STATE_REAL)
    firstname = models.CharField(verbose_name='نام', max_length=50)
    lastname = models.CharField(verbose_name='نام خانوادگی', max_length=50)
    fathername = models.CharField(verbose_name='نام پدر', max_length=50)
    code = models.CharField(verbose_name='کدملی', max_length=10)
    ceoname = models.CharField(verbose_name='نام مدیرعامل', max_length=100, null=True, blank=True)
    company = models.CharField(verbose_name='نام تجاری/شرکت', max_length=100)
    ncode = models.CharField(verbose_name='شناسه ملی', max_length=11, null=True, blank=True)
    mobile = models.CharField(verbose_name='موبایل', max_length=11)
    phone = models.CharField(verbose_name='تلفن', max_length=11, null=True, blank=True)
    fax = models.CharField(verbose_name='فکس', max_length=11, null=True, blank=True)
    email = models.EmailField(verbose_name='ایمیل', null=True, blank=True)
    postalcode = models.CharField(verbose_name='کد پستی', max_length=10)
    address = models.TextField(verbose_name='آدرس')

    def __str__(self):
        return f"{self.company}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["company", "code"], name='comcode'),
            models.UniqueConstraint(fields=["sid"], name='specid')
    ]
        verbose_name = 'مشارکت کننده'
        verbose_name_plural = 'مشارکت کنندگان'


class DocumentsModel(BaseModel):
    STATE_WAIT = 'wait'
    STATE_ACCEPT = 'accept'
    STATE_DENY = 'deny'
    STATE_CHOICES = (
        (STATE_WAIT, 'در انتظار بررسی'),
        (STATE_ACCEPT, 'قبول شده'),
        (STATE_DENY, 'رد شده')
    )
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_WAIT)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='مشارکت کننده')
    file = models.FileField(verbose_name='مدرک', upload_to=documents_directory_path)

    def __str__(self):
        if self.customer is not None:
            return f"{self.customer.company} - {self.file.name}"
        return self.file.name
    
    class Meta:
        verbose_name = 'مدرک'
        verbose_name_plural = 'مدارک'


class ExhibitionModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    sid = models.CharField(verbose_name='کد معین', max_length=50, null=True, blank=True)
    title = models.CharField(verbose_name='عنوان نمایشگاه', max_length=200)
    price = models.CharField(verbose_name='قیمت', max_length=20)
    value_added = models.CharField(verbose_name='ارزش افزوده', max_length=10)
    date = models.DateField(verbose_name='تاریخ برگزاری', null=True, blank=True)

    def __str__(self):
        return f"{self.title} - {self.date.year}"
    
    class Meta:
        verbose_name = 'نمایشگاه'
        verbose_name_plural = 'نمایشگاه‌ها'


class RequestModel(BaseModel):
    STATE_WAIT = 'wait'
    STATE_ACCEPT = 'accept'
    STATE_DENY = 'deny'
    STATE_CHOICES = (
        (STATE_WAIT, 'در انتظار بررسی'),
        (STATE_ACCEPT, 'قبول شده'),
        (STATE_DENY, 'رد شده')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_WAIT)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, verbose_name='مشارکت کننده')
    exhibition = models.ForeignKey(ExhibitionModel, on_delete=models.CASCADE, verbose_name='نمایشگاه')
    area = models.IntegerField(verbose_name='متراژ', default=0)
    rules = models.BooleanField(verbose_name='قوانین')
    is_active = models.BooleanField(verbose_name='فعال', default=True)

    def __str__(self):
        return f"{self.customer.company} - {self.exhibition.title}"
    
    class Meta:
        verbose_name = 'درخواست'
        verbose_name_plural = 'درخواست‌ها'


class MessagesModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=True)
    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE, verbose_name='مشارکت کننده')
    text = models.TextField(verbose_name='متن پیام')

    def __str__(self):
        return f"{self.pk}.{self.customer.company} - ({self.customer.firstname} {self.customer.lastname})"
    
    class Meta:
        verbose_name = 'پیغام'
        verbose_name_plural = 'پیغام‌ها'


class MessageChangeModel(models.Model):
    message = models.ForeignKey(MessagesModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="پیغام اصلی")
    text = models.TextField(verbose_name='متن پیام')
    user_modified = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_user_modified',
        null=True,
        blank=True,
        verbose_name='کاربر ویرایش'
        )
    modified_date = models.DateTimeField(verbose_name='تاریخ تغییرات')

    def __str__(self):
        if self.message is not None:
            return f"{self.message.pk}.{self.message.customer.company} - ({self.message.customer.firstname} {self.message.customer.lastname})"
        return self.text
    
    class Meta:
        verbose_name = 'پیغام ویرایش شده'
        verbose_name_plural = 'پیغام‌های ویرایشی'


class InvoiceModel(BaseModel):
    STATE_PREPAYMENT = 'prepayment'
    STATE_PAID = 'paid'
    STATE_UNPAID = 'unpaid'
    STATE_CHOICES = (
        (STATE_PREPAYMENT, 'پیش پرداخت'),
        (STATE_PAID, 'پرداخت شده'),
        (STATE_UNPAID, 'پرداخت نشده')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_UNPAID)
    customer = models.ForeignKey(CustomerModel, on_delete=models.PROTECT, verbose_name="مشارکت کننده")
    amount = models.CharField(verbose_name="مبلغ", max_length=20)

    def __str__(self):
        return f"{self.customer.company} - شماره فاکتور: {self.pk}"
    
    class Meta:
        verbose_name = 'فاکتور'
        verbose_name_plural = 'فاکتورها'


class InvoiceItemModel(BaseModel):
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    invoice = models.ForeignKey(InvoiceModel, on_delete=models.SET_NULL, verbose_name="فاکتور", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='کاربر')
    customer = models.ForeignKey(CustomerModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='مشارکت کننده')
    exhibition = models.ForeignKey(ExhibitionModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='نمایشگاه')
    price = models.CharField(verbose_name='مبلغ', max_length=20)
    area = models.IntegerField(verbose_name='متراژ', default=0)
    value_added = models.CharField(verbose_name='ارزش افزوده', max_length=10, default="0")
    discount = models.CharField(verbose_name='تخفیف', max_length=20, null=True, blank=True)
    total_price = models.CharField(verbose_name='مبلغ نهایی', max_length=20)
    description = models.TextField(verbose_name='توضیحات', null=True, blank=True)

    def __str__(self):
        if self.customer is not None:
            return f"{self.customer.company} - {self.exhibition.title} - {self.price}"
        return f"{self.area} - {self.total_price}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["exhibition", "customer"], name='excus')
    ]
        verbose_name = 'اقلام فاکتور'
        verbose_name_plural = 'اقلام فاکتورها'


class PaymentModel(BaseModel):
    STATE_CHECK = 'check'
    STATE_CASHE = 'cashe'
    STATE_POS = 'pos'
    STATE_CHOICES = (
        (STATE_CHECK, 'چک بانکی'),
        (STATE_CASHE, 'نقدی'),
        (STATE_POS, 'پوز بانکی')
    )
    state = models.CharField(verbose_name='وضعیت', max_length=50, choices=STATE_CHOICES, default=STATE_POS)
    invoice = models.ForeignKey(InvoiceModel, on_delete=models.PROTECT, verbose_name="فاکتور")
    amount = models.IntegerField(verbose_name="مبلغ", default=1000)
    cardnumber = models.CharField(verbose_name="شماره کارت/چک", max_length=32, null=True, blank=True)
    issuerbank = models.CharField(verbose_name="بانک صادرکننده", max_length=150, null=True, blank=True)
    name = models.CharField(verbose_name="مشخصات صاحب چک", max_length=150, null=True, blank=True)

staff/models.py
from django.db import models

# Create your models here.

staff/templates/staff/documents-list.html
{% extends "base.html" %}
{% load jalali_tags %}
{% load static %}

{% block title %}
لیست مدارک مشارکت کنندگان
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body" data-bg-image="{% static 'images/docs.png' %}">
                        <h2>لیست مدارک</h2>
                        <p>لطفا مدارک بارگذاری شده را با دقت بررسی کرده و وضعیت آنهارا مشخص کنید.</p>
                        <p class="text-danger">توجه! درصورت استفاده از گزینه حذف، مدرک بارگذاری شده پاک شده و قابلیت بازگشت ندارد.</p>
                    </div>
                </div>
            </div>
            {% if messages %}
            <div class="col-lg-12">
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div role="alert" class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> هشدار!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                        <div role="alert" class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> تبریک!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <div class="row">
                                    <div class="form-group col-lg-2">
                                        <input class="form-control" id="myInput" type="text" placeholder="جستجو...">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="table-responsive" style="height:500px;overflow:auto;">
                                    <table id="datatable" class="table table-bordered table-hover" style="width:100%">
                                        <thead class="thead-light">
                                            <tr>
                                                <th>کد</th>
                                                <th>وضعیت</th>
                                                <th>نام تجاری</th>
                                                <th>نام و نشان</th>
                                                <th>مدارک</th>
                                                <th>تاریخ</th>
                                                <th>اقدامات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for doc in doc %}
                                            <tr>
                                                <td>{{ doc.pk }}</td>
                                                <td>
                                                    {% if doc.state == "wait" %}
                                                    <span class="badge badge-pill badge-warning">در انتظار بررسی</span>
                                                    {% elif doc.state == "accept"  %}
                                                    <span class="badge badge-pill badge-success">قبول</span>
                                                    {% else %}
                                                    <span class="badge badge-pill badge-danger">رد شده</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <a href="{% url 'staff:customer-change' cid=doc.customer.pk %}" style="color:blueviolet">{{ doc.customer.company }}</a>
                                                </td>
                                                <td class="text-info">{{ doc.customer.firstname }} {{ doc.customer.lastname }}</td>
                                                <td><a href="{{ doc.file.url }}" target="_blank">{{ doc.file.name|cut:doc.customer.company }}</a></td>
                                                <td style="color:#003f5c">{{ doc.created_date|to_jalali:'%Y/%m/%d' }}</td>
                                                <td>
                                                    <a class="mr-2 text-success" href="{% url 'staff:documents-accept' fid=doc.pk %}" data-toggle="tooltip" data-original-title="تایید"><i class="icon-check" style="font-size:large"></i></a>
                                                    <a class="mr-2 text-danger" href="{% url 'staff:documents-deny' fid=doc.pk %}" data-toggle="tooltip" data-original-title="عدم تایید"><i class="icon-x-square" style="font-size:large"></i></a>
                                                    <a class="mr-2 text-info" href="{% url 'staff:documents-del' fid=doc.pk %}" data-toggle="tooltip" data-original-title="حذف"><i class="icon-trash-2" style="font-size:large"></i></a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            {% comment %} <div class="col-lg-3 text-center">
                                <img src="{% static 'images/doclist.png' %}">
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block script %}

<script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#datatable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>
{% endblock script %}

staff/templates/staff/messages-list.html
{% extends "base.html" %}
{% load jalali_tags %}
{% load static %}

{% block title %}
 پیغام های ارسال شده
{% endblock title %}

{% block content %}
<section id="page-content" class="background-light">
    <div class="container-fluid">
        <div class="row">
            {% if messages %}
            <div class="col-lg-12">
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div role="alert" class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> هشدار!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                    {% if message.tags == 'success' %}
                        <div role="alert" class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                            <strong><i class="fa fa-exclamation-circle"></i> تبریک!</strong> 
                            {{ message}}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            {% if form.non_field_errors %}
            <div class="col-lg-12">
                {% for error in form.non_field_errors %}
                <div role="alert" class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                    <strong><i class="fa fa-exclamation-circle"></i> خطا!</strong> 
                    {{ error }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="mb-3 text-success">ارسال پیغام جدید</h3>
                        <div class="row">
                            <div class="col-lg-8">
                                <form method="post" action="{% url 'staff:message-add' %}">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="form-group col-lg-2">
                                            {{ form.customer.label_tag }}
                                            {{ form.customer }}
                                            {% if form.label_tag.errors %}
                                                {% for error in form.label_tag.errors %}
                                                    <p class="text-danger">{{ error }}</p>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-lg-8">
                                            {{ form.text.label_tag }}
                                            {{ form.text }}
                                            {% if form.label_tag.errors %}
                                                {% for error in form.label_tag.errors %}
                                                    <p class="text-danger">{{ error }}</p>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <input type="submit" class="btn btn-success" value="ارسال">
                                </form>
                            </div>
                            <div class="col-lg-4 text-center">
                                <img src="{% static 'images/message.png' %}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="mb-3">لیست پیغام‌ها</h3>
                        <div class="row">
                            <div class="form-group col-lg-3">
                                <input class="form-control" id="myInput" type="text" placeholder="جستجو...">
                            </div>
                            <div class="col-lg-12">
                                <div class="table-responsive" style="height:500px;overflow:auto;">
                                    <table id="datatable" class="table table-bordered table-hover" style="width:100%">
                                        <thead class="thead-light">
                                            <tr>
                                                <th>کد</th>
                                                <th>کاربر ایجاد</th>
                                                <th>مشارکت کننده</th>
                                                <th>متن پیغام</th>
                                                <th>تاریخ ایجاد</th>
                                                <th>تاریخ آخرین تغییرات</th>
                                                <th>وضعیت</th>
                                                <th>اقدامات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for mes in mes %}
                                            <tr>
                                                <td>{{ mes.pk }}</td>
                                                <td data-toggle="tooltip" data-placement="top" title="{{ mes.user_created.first_name }} {{ mes.user_created.last_name }}">
                                                    <code>{{ mes.user_created.username }}</code>
                                                </td>
                                                <td style="color:blueviolet" data-toggle="tooltip" data-placement="top" title="{{ mes.customer.firstname }} {{ mes.customer.lastname }}">
                                                {{ mes.customer.company }}
                                                </td>
                                                <td class="text-primary" data-toggle="tooltip" data-placement="top" title="{{ mes.text }}">{{ mes.text|truncatewords:12 }}</td>
                                                <td>{{ mes.created_date|to_jalali:'%H:%M - %Y/%m/%d' }}</td>
                                                <td>{{ mes.modified_date|to_jalali:'%H:%M - %Y/%m/%d' }}</td>
                                                <td>{% if mes.is_active %}
                                                    <h4><span class="badge badge-pill badge-warning">ارسال شده</span></h4>
                                                    {% else %}
                                                    <h4><span class="badge badge-pill badge-success">خوانده شده</span></h4>
                                                    {% endif %}
                                                </td>
                                                {% if mes.is_active %}
                                                <td class="text-center"><a href="{% url 'staff:message-change' mid=mes.pk %}"><i class="fa fa-edit"></i></a></td>
                                                {% else %}
                                                <td class="text-center text-danger"><i class="fa fa-minus-circle"> </i></td>
                                                {% endif %}
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block script %}

<script src={% static 'plugins/datatables/datatables.min.js' %}></script>
<script>
    $(document).ready(function(){
      $("#myInput").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#datatable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
    </script>
    <script>
        // Initialize Select2 on the select element
        $(document).ready(function() {
          $('#id_user').select2();
        });
      </script>
{% endblock script %}

staff/templates/staff/none.html
{% extends "base.html" %}
{% load static %}
{% block title %}

{% endblock title %}
{% block content %}
<section class="m-t-80 p-b-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div data-bg-image="{% static 'images/error.png' %}" style="height:400px">

                </div>
            </div>
            <div class="col-lg-6">
                <div class="text-left">
                    {% if title %}
                    <h1 class="text-medium">{{ title }}</h1>
                    {% endif %}
                    {% if content %}
                    <p class="lead">{{ content }}</p>
                    {% endif %}
                    <div class="seperator m-t-20 m-b-20"></div>
                    <div class="search-form">
                        <p>لطفا دوباره جستجو کنید</p>
                        <form action="search-results-page.html" method="get" class="form-inline">
                            <div class="input-group input-group-lg">
                                <input type="text" aria-required="true" name="q" class="form-control widget-search-form" placeholder="جستجو کنید ...">
                                <div class="input-group-append">
                                    <span class="input-group-btn">
                                        <button type="submit" id="widget-widget-search-form-button" class="btn"><i class="fa fa-search"></i></button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}